version: '3.8'

services:
  pact-broker:
    image: pactfoundation/pact-broker
    ports:
      - "9292:9292"
    environment:
      - PACT_BROKER_DATABASE_URL=postgresql://postgres:postgres@db:5432/pact_broker
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pact_broker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fishery-pact:
    build:
      context: ./tests/fishery-pact
      dockerfile: Dockerfile
    volumes:
      - ./tests/fishery-pact:/app
      - ./client:/client
    environment:
      - PACT_BROKER_URL=http://pact-broker:9292
      - NODE_ENV=test
    depends_on:
      - pact-broker

  uav-pact:
    build:
      context: ./tests/uav-pact
      dockerfile: Dockerfile
    volumes:
      - ./tests/uav-pact:/app
      - ./client:/client
    environment:
      - PACT_BROKER_URL=http://pact-broker:9292
      - NODE_ENV=test
    depends_on:
      - pact-broker 